version: '3'

services:
  app:
    container_name: app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - phpmyadmin
    links:
      - phpmyadmin

  phpmyadmin:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: phalcon_app
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    ports:
      - '3307:3306'