version: '3'

services:
  app:
    container_name: app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    container_name: mariadb-new